XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_DATA_HOME=$HOME/.local/share

ZDOTDIR=$XDG_CONFIG_HOME/zsh
HISTFILE=$XDG_DATA_HOME/zsh/history

ZGEN_DIR=$ZDOTDIR/zgen
POWERLEVEL9K_CONFIG_FILE=$ZDOTDIR/.p10k.zsh
